
services:
  app:
    build: .
    container_name: my_blog_app_container
    volumes:
      - .:/var/www/html   
    networks:
      - my_blog_net

  nginx:
    image: nginx:latest
    container_name: my_blog_nginx_container
    ports:
      - "8000:80"
    # volumes:
    #   - ./nginx/conf:/etc/nginx/conf.d   
    #   - .:/var/www/html               
    #   - ./logs/nginx:/var/log/nginx      
    depends_on:
      - app
    networks:
      - my_blog_net

networks:
  my_blog_net:
    driver: bridge
