
services:
  app:
    build:
      context: .
      dockerfile: ./Deployment/my_blog_app/Dockerfile
    container_name: my_blog_app_container
    volumes:
      - .:/var/www/html   
    networks:
      - my_blog_net

  nginx:
      build:
        context: ./Deployment/nginx
      container_name: my_blog_nginx_container
      ports:
        - "8000:80"
      depends_on:
        - app
      networks:
        - my_blog_net


networks:
  my_blog_net:
    driver: bridge
