

services:
  php-app:
    build: .
    ports:
      - "8081:8000" 
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=host.docker.internal
    env_file:
      - .env
    networks:
      - hostnet
    restart: unless-stopped

networks:
  hostnet:
    driver: bridge